{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "\n",
       "<textarea rows=5 id=nav_head_content style=\"width:100%;display:none;\">\n",
       "<style>\n",
       "a.bh,  a.bh:visited, a.bh:link, a.bh:active {\n",
       "  ttext-decoration: none; \n",
       "  color: black;\n",
       "  font-family: 'Roboto','Heebo',Arial,sans-serif;\n",
       "  font-size: 3em\n",
       "}\n",
       "</style>\n",
       "<div id='HTMLTopBar' style=\"    \n",
       "    z-index: 50;\n",
       "    align-items: stretch;\n",
       "    width:100%\">\n",
       "    <div  style=\"\n",
       "        text-color: black;\n",
       "        background-color: #fefefe;\n",
       "        bborder-bottom: 1px dotted gray;\n",
       "        padding-left: 2px;\n",
       "        box-shadow: 5px 1px #ccc;\n",
       "        height: 40px; left: 0; \n",
       "        padding: 14px;\n",
       "        \"\n",
       "    >\n",
       "    <a class=bh1 href=\"#\" onclick=\"$('#maintoolbar').toggle();\">X</a>\n",
       "</div>\n",
       "</textarea>\n",
       "\n",
       "<script>\n",
       "if ($('#nav_head').length < 1) {\n",
       "    $('#notebook-container').prepend('<div id=\"nav_head\" style=\"width:100%;\">.</div>')\n",
       "    console.log(\"Added a div\")\n",
       "} else{\n",
       "    console.log(\"Already Added\")    \n",
       "}\n",
       "\n",
       "$('#nav_head').html($('#nav_head_content').val())\n",
       "\n",
       "$('.nbp-app-bar').toggle()\n",
       "</script>\n"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<style>\n",
       "@import url('https://fonts.googleapis.com/css2?family=Roboto&display=swap');\n",
       "</style>\n",
       "<style>\n",
       "<link href=\"https://fonts.googleapis.com/css2?family=Roboto&display=swap\" \n",
       "                            rel=\"stylesheet\">\n",
       "\n",
       "body  p ol li {\n",
       "    font-family: \"Roboto\",  \"Lucida Grande\", \"Lucida Sans Unicode\";\n",
       "    font-size: 14px;\n",
       "    background: #fff\n",
       "}\n",
       "\n",
       "h1, h2, h3{\n",
       "    font-family: 'Roboto', sans-serif;\n",
       "}\n",
       "div#notebook_panel div#notebook{\n",
       "    background: #ffffff\n",
       "}\n",
       "div#notebook-container{\n",
       "    box-shadow: 0px;\n",
       "    padding: 0px;\n",
       "    border-left: .05em dotted gray;\n",
       "    -webkit-box-shadow: 0px;\n",
       "    box-shadow: none;\n",
       "}\n",
       "</style>\n"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<style>\n",
       ".container { width: 100% !important; }\n",
       "    div.cell{\n",
       "        width:100%;\n",
       "        margin-left:0%;\n",
       "        margin-right:auto;\n",
       "}\n",
       ".CodeMirror {\n",
       "    font-family: monospace;\n",
       "}\n",
       "div.input_area {\n",
       "    border: 0px;\n",
       "}\n",
       "div.cell.selected{\n",
       "  border: '0px';\n",
       "}\n",
       ".cell.selected{\n",
       "  border: '0px';\n",
       "}\n",
       "div#notebook{\n",
       "    padding-top: 0px;\n",
       "}\n",
       "div.prompt_container {\n",
       "    display: block; \n",
       "    background: #f7f7f7;\n",
       "}\n",
       "div.prompt{\n",
       "    min-width:0px;\n",
       "    display: grid;\n",
       "}\n",
       "div.cell{\n",
       "    padding-bottom: 5px;\n",
       "    padding-left: 0px;\n",
       "}\n",
       "\n",
       "a.bh,  a.bh:visited, a.bh:link, a.bh:active {\n",
       "  text-decoration: none; \n",
       "  color:white;\n",
       "  font-family: 'Roboto','Heebo',Arial,sans-serif;\n",
       "  font-size:1em\n",
       "}\n",
       "a.bh:hover {\n",
       "  color: #ffccdd;\n",
       "}\n",
       "\n",
       "a.bh1,  a.bh1:visited, a.bh1:link, a.bh1:active {\n",
       "  text-decoration: none; \n",
       "  color: rgba(0, 0, 0, 0.87);\n",
       "  font-family: 'Roboto','Heebo',Arial,sans-serif;\n",
       "  padding-right: 30px;\n",
       "  font-size:1.1em\n",
       "}\n",
       "a.bh1:hover {\n",
       "  color: rgba(0, 0, 0, 0.57);\n",
       "}\n",
       "    \n",
       "#toc-wrapper {\n",
       "   font-family: 'Roboto','Heebo',Arial,sans-serif;\n",
       "    border: 0px dotted gray;\n",
       "    padding: 10px;\n",
       "    line-height: 1.8em;\n",
       "}    \n",
       "</style>\n",
       "<script>\n",
       "l=\"https://www.ancient-symbols.com/images/wp-image-library/fullsize/infinity.jpg\"\n",
       "l=\"imgs/logo.png\"\n",
       "l=\"\"\n",
       "$('#ipython_notebook').html(`<img src=\"${l}\">`)\n",
       "\n",
       "</script>\n"
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    }
   ],
   "source": [
    "%reload_ext autoreload\n",
    "%autoreload 2\n",
    "import colabexts\n",
    "from colabexts.jcommon import *\n",
    "\n",
    "jpath=os.path.dirname(colabexts.__file__)\n",
    "jcom = f'{jpath}/jcommon.ipynb'\n",
    "%run $jcom\n",
    "\n",
    "import os, sys, datetime, re, json, importlib\n",
    "from collections import defaultdict\n",
    "from sys import modules\n",
    "from IPython.display import HTML, Javascript\n",
    "import warnings\n",
    "import pandas as pd\n",
    "warnings.filterwarnings('ignore')\n",
    "\n",
    "%matplotlib inline\n",
    "pd.set_option('display.max_colwidth', 8)\n",
    "pd.set_option('display.max_rows', 8)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of django.conf failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 330, in update_generic\n",
      "    if type_check(a, b):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 316, in <lambda>\n",
      "    (lambda a, b: isinstance2(a, b, type),\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 312, in isinstance2\n",
      "    return isinstance(a, typ) and isinstance(b, typ)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 224, in inner\n",
      "    return decorator\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/conf/__init__.py\", line 68, in _setup\n",
      "    % (desc, ENVIRONMENT_VARIABLE))\n",
      "django.core.exceptions.ImproperlyConfigured: Requested settings, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.\n",
      "]\n",
      "[autoreload of django.utils.translation failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 378, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/translation/__init__.py\", line 11, in <module>\n",
      "    from django.utils.regex_helper import _lazy_re_compile\n",
      "ImportError: cannot import name '_lazy_re_compile' from 'django.utils.regex_helper' (/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/regex_helper.py)\n",
      "]\n",
      "[autoreload of django.http.request failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 378, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/http/request.py\", line 23, in <module>\n",
      "    from django.utils.regex_helper import _lazy_re_compile\n",
      "ImportError: cannot import name '_lazy_re_compile' from 'django.utils.regex_helper' (/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/regex_helper.py)\n",
      "]\n",
      "[autoreload of django.core.signing failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 378, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/core/signing.py\", line 47, in <module>\n",
      "    from django.utils.regex_helper import _lazy_re_compile\n",
      "ImportError: cannot import name '_lazy_re_compile' from 'django.utils.regex_helper' (/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/regex_helper.py)\n",
      "]\n",
      "[autoreload of django.utils.http failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 378, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/http.py\", line 19, in <module>\n",
      "    from django.utils.regex_helper import _lazy_re_compile\n",
      "ImportError: cannot import name '_lazy_re_compile' from 'django.utils.regex_helper' (/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/regex_helper.py)\n",
      "]\n",
      "[autoreload of django.http.response failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 378, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/http/response.py\", line 20, in <module>\n",
      "    from django.utils.regex_helper import _lazy_re_compile\n",
      "ImportError: cannot import name '_lazy_re_compile' from 'django.utils.regex_helper' (/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/regex_helper.py)\n",
      "]\n",
      "[autoreload of django.db.models failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 378, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/db/models/__init__.py\", line 7, in <module>\n",
      "    from django.db.models.deletion import (\n",
      "ImportError: cannot import name 'RESTRICT' from 'django.db.models.deletion' (/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/db/models/deletion.py)\n",
      "]\n",
      "[autoreload of django.db.models.fields failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 331, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 279, in update_class\n",
      "    if (old_obj == new_obj) is True:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 148, in __eq__\n",
      "    def __cast(self):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 136, in __cast\n",
      "    return getattr(res, method_name)(*args, **kw)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 124, in __text_cast\n",
      "    if cls._delegate_text:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/translation/__init__.py\", line 92, in gettext\n",
      "    return _trans.gettext(message)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/translation/__init__.py\", line 57, in __getattr__\n",
      "    if settings.USE_I18N:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/conf/__init__.py\", line 83, in __getattr__\n",
      "    self._setup(name)\n",
      "django.core.exceptions.ImproperlyConfigured: Requested setting USE_I18N, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.\n",
      "]\n",
      "[autoreload of django.utils.html failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 378, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/html.py\", line 14, in <module>\n",
      "    from django.utils.regex_helper import _lazy_re_compile\n",
      "ImportError: cannot import name '_lazy_re_compile' from 'django.utils.regex_helper' (/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/regex_helper.py)\n",
      "]\n",
      "[autoreload of django.utils.text failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 378, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/text.py\", line 10, in <module>\n",
      "    from django.utils.regex_helper import _lazy_re_compile\n",
      "ImportError: cannot import name '_lazy_re_compile' from 'django.utils.regex_helper' (/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/regex_helper.py)\n",
      "]\n",
      "[autoreload of django.forms.widgets failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 378, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/forms/widgets.py\", line 19, in <module>\n",
      "    from django.utils.regex_helper import _lazy_re_compile\n",
      "ImportError: cannot import name '_lazy_re_compile' from 'django.utils.regex_helper' (/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/regex_helper.py)\n",
      "]\n",
      "[autoreload of django.template.base failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 378, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/template/base.py\", line 61, in <module>\n",
      "    from django.utils.regex_helper import _lazy_re_compile\n",
      "ImportError: cannot import name '_lazy_re_compile' from 'django.utils.regex_helper' (/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/regex_helper.py)\n",
      "]\n",
      "[autoreload of django.utils.dateformat failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 378, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/dateformat.py\", line 21, in <module>\n",
      "    from django.utils.regex_helper import _lazy_re_compile\n",
      "ImportError: cannot import name '_lazy_re_compile' from 'django.utils.regex_helper' (/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/regex_helper.py)\n",
      "]\n",
      "[autoreload of django.utils.datetime_safe failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 378, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/datetime_safe.py\", line 15, in <module>\n",
      "    from django.utils.regex_helper import _lazy_re_compile\n",
      "ImportError: cannot import name '_lazy_re_compile' from 'django.utils.regex_helper' (/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/regex_helper.py)\n",
      "]\n",
      "[autoreload of django.forms.fields failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 378, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/forms/fields.py\", line 32, in <module>\n",
      "    from django.utils.regex_helper import _lazy_re_compile\n",
      "ImportError: cannot import name '_lazy_re_compile' from 'django.utils.regex_helper' (/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/regex_helper.py)\n",
      "]\n",
      "[autoreload of django.core.validators failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 378, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/core/validators.py\", line 10, in <module>\n",
      "    from django.utils.regex_helper import _lazy_re_compile\n",
      "ImportError: cannot import name '_lazy_re_compile' from 'django.utils.regex_helper' (/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/regex_helper.py)\n",
      "]\n",
      "[autoreload of django.utils.dateparse failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 378, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/dateparse.py\", line 10, in <module>\n",
      "    from django.utils.regex_helper import _lazy_re_compile\n",
      "ImportError: cannot import name '_lazy_re_compile' from 'django.utils.regex_helper' (/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/regex_helper.py)\n",
      "]\n",
      "[autoreload of django.forms.models failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 331, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 279, in update_class\n",
      "    if (old_obj == new_obj) is True:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 148, in __eq__\n",
      "    def __cast(self):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 136, in __cast\n",
      "    return getattr(res, method_name)(*args, **kw)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 124, in __text_cast\n",
      "    if cls._delegate_text:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/translation/__init__.py\", line 92, in gettext\n",
      "    return _trans.gettext(message)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/translation/__init__.py\", line 57, in __getattr__\n",
      "    if settings.USE_I18N:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/conf/__init__.py\", line 83, in __getattr__\n",
      "    self._setup(name)\n",
      "django.core.exceptions.ImproperlyConfigured: Requested setting USE_I18N, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.\n",
      "]\n",
      "[autoreload of django.core.checks failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 378, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/core/checks/__init__.py\", line 8, in <module>\n",
      "    import django.core.checks.async_checks  # NOQA isort:skip\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/core/checks/async_checks.py\", line 12, in <module>\n",
      "    @register(Tags.async_support, deploy=True)\n",
      "AttributeError: type object 'Tags' has no attribute 'async_support'\n",
      "]\n",
      "[autoreload of django.core.cache failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 378, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/core/cache/__init__.py\", line 19, in <module>\n",
      "    from django.core.cache.backends.base import (\n",
      "ImportError: cannot import name 'InvalidCacheKey' from 'django.core.cache.backends.base' (/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/core/cache/backends/base.py)\n",
      "]\n",
      "[autoreload of django.utils.translation.trans_real failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 378, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/translation/trans_real.py\", line 17, in <module>\n",
      "    from django.utils.regex_helper import _lazy_re_compile\n",
      "ImportError: cannot import name '_lazy_re_compile' from 'django.utils.regex_helper' (/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/regex_helper.py)\n",
      "]\n",
      "[autoreload of django.db.models.functions failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 378, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/db/models/functions/__init__.py\", line 2, in <module>\n",
      "    from .datetime import (\n",
      "ImportError: cannot import name 'ExtractIsoWeekDay' from 'django.db.models.functions.datetime' (/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/db/models/functions/datetime.py)\n",
      "]\n",
      "[autoreload of django.db.models.constraints failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 331, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 289, in update_class\n",
      "    if update_generic(old_obj, new_obj): continue\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 331, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 265, in update_function\n",
      "    setattr(old, name, getattr(new, name))\n",
      "ValueError: __eq__() requires a code object with 0 free vars, not 1\n",
      "]\n",
      "[autoreload of django.db.models.fields.files failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 331, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 279, in update_class\n",
      "    if (old_obj == new_obj) is True:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 148, in __eq__\n",
      "    def __cast(self):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 136, in __cast\n",
      "    return getattr(res, method_name)(*args, **kw)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 124, in __text_cast\n",
      "    if cls._delegate_text:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/translation/__init__.py\", line 92, in gettext\n",
      "    return _trans.gettext(message)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/translation/__init__.py\", line 57, in __getattr__\n",
      "    if settings.USE_I18N:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/conf/__init__.py\", line 83, in __getattr__\n",
      "    self._setup(name)\n",
      "django.core.exceptions.ImproperlyConfigured: Requested setting USE_I18N, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.\n",
      "]\n",
      "[autoreload of django.db.models.fields.related failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 331, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 279, in update_class\n",
      "    if (old_obj == new_obj) is True:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 148, in __eq__\n",
      "    def __cast(self):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 136, in __cast\n",
      "    return getattr(res, method_name)(*args, **kw)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 124, in __text_cast\n",
      "    if cls._delegate_text:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/translation/__init__.py\", line 92, in gettext\n",
      "    return _trans.gettext(message)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/translation/__init__.py\", line 57, in __getattr__\n",
      "    if settings.USE_I18N:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/conf/__init__.py\", line 83, in __getattr__\n",
      "    self._setup(name)\n",
      "django.core.exceptions.ImproperlyConfigured: Requested setting USE_I18N, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.\n",
      "]\n",
      "[autoreload of django.urls.resolvers failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 378, in superreload\n",
      "    module = reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/imp.py\", line 314, in reload\n",
      "    return importlib.reload(module)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/importlib/__init__.py\", line 169, in reload\n",
      "    _bootstrap._exec(spec, module)\n",
      "  File \"<frozen importlib._bootstrap>\", line 630, in _exec\n",
      "  File \"<frozen importlib._bootstrap_external>\", line 728, in exec_module\n",
      "  File \"<frozen importlib._bootstrap>\", line 219, in _call_with_frames_removed\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/urls/resolvers.py\", line 24, in <module>\n",
      "    from django.utils.regex_helper import _lazy_re_compile, normalize\n",
      "ImportError: cannot import name '_lazy_re_compile' from 'django.utils.regex_helper' (/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/regex_helper.py)\n",
      "]\n",
      "[autoreload of django.db.models.fields failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 331, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 279, in update_class\n",
      "    if (old_obj == new_obj) is True:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 147, in __eq__\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 152, in __cast\n",
      "    return self.__text_cast()\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 140, in __text_cast\n",
      "    return func(*self.__args, **self.__kw)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/translation/__init__.py\", line 92, in gettext\n",
      "    return _trans.gettext(message)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/translation/__init__.py\", line 57, in __getattr__\n",
      "    if settings.USE_I18N:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/conf/__init__.py\", line 83, in __getattr__\n",
      "    self._setup(name)\n",
      "django.core.exceptions.ImproperlyConfigured: Requested setting USE_I18N, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.\n",
      "]\n",
      "[autoreload of django.forms.widgets failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 331, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 279, in update_class\n",
      "    if (old_obj == new_obj) is True:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 147, in __eq__\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 152, in __cast\n",
      "    return self.__text_cast()\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 140, in __text_cast\n",
      "    return func(*self.__args, **self.__kw)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/translation/__init__.py\", line 92, in gettext\n",
      "    return _trans.gettext(message)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/translation/__init__.py\", line 57, in __getattr__\n",
      "    if settings.USE_I18N:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/conf/__init__.py\", line 83, in __getattr__\n",
      "    self._setup(name)\n",
      "django.core.exceptions.ImproperlyConfigured: Requested setting USE_I18N, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.\n",
      "]\n",
      "[autoreload of django.forms.fields failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 331, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 279, in update_class\n",
      "    if (old_obj == new_obj) is True:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 147, in __eq__\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 152, in __cast\n",
      "    return self.__text_cast()\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 140, in __text_cast\n",
      "    return func(*self.__args, **self.__kw)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/translation/__init__.py\", line 92, in gettext\n",
      "    return _trans.gettext(message)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/translation/__init__.py\", line 57, in __getattr__\n",
      "    if settings.USE_I18N:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/conf/__init__.py\", line 83, in __getattr__\n",
      "    self._setup(name)\n",
      "django.core.exceptions.ImproperlyConfigured: Requested setting USE_I18N, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.\n",
      "]\n",
      "[autoreload of django.core.validators failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 331, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 279, in update_class\n",
      "    if (old_obj == new_obj) is True:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 147, in __eq__\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 152, in __cast\n",
      "    return self.__text_cast()\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 140, in __text_cast\n",
      "    return func(*self.__args, **self.__kw)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/translation/__init__.py\", line 92, in gettext\n",
      "    return _trans.gettext(message)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/translation/__init__.py\", line 57, in __getattr__\n",
      "    if settings.USE_I18N:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/conf/__init__.py\", line 83, in __getattr__\n",
      "    self._setup(name)\n",
      "django.core.exceptions.ImproperlyConfigured: Requested setting USE_I18N, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.\n",
      "]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Overwriting mangorest/mango.py\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "[autoreload of django.forms.models failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 331, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 279, in update_class\n",
      "    if (old_obj == new_obj) is True:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 147, in __eq__\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 152, in __cast\n",
      "    return self.__text_cast()\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 140, in __text_cast\n",
      "    return func(*self.__args, **self.__kw)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/translation/__init__.py\", line 92, in gettext\n",
      "    return _trans.gettext(message)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/translation/__init__.py\", line 57, in __getattr__\n",
      "    if settings.USE_I18N:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/conf/__init__.py\", line 83, in __getattr__\n",
      "    self._setup(name)\n",
      "django.core.exceptions.ImproperlyConfigured: Requested setting USE_I18N, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.\n",
      "]\n",
      "[autoreload of django.db.models.fields.files failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 331, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 279, in update_class\n",
      "    if (old_obj == new_obj) is True:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 147, in __eq__\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 152, in __cast\n",
      "    return self.__text_cast()\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 140, in __text_cast\n",
      "    return func(*self.__args, **self.__kw)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/translation/__init__.py\", line 92, in gettext\n",
      "    return _trans.gettext(message)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/translation/__init__.py\", line 57, in __getattr__\n",
      "    if settings.USE_I18N:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/conf/__init__.py\", line 83, in __getattr__\n",
      "    self._setup(name)\n",
      "django.core.exceptions.ImproperlyConfigured: Requested setting USE_I18N, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.\n",
      "]\n",
      "[autoreload of django.db.models.fields.related failed: Traceback (most recent call last):\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 244, in check\n",
      "    superreload(m, reload, self.old_objects)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 394, in superreload\n",
      "    update_generic(old_obj, new_obj)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 331, in update_generic\n",
      "    update(a, b)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/IPython/extensions/autoreload.py\", line 279, in update_class\n",
      "    if (old_obj == new_obj) is True:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 147, in __eq__\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 152, in __cast\n",
      "    return self.__text_cast()\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/functional.py\", line 140, in __text_cast\n",
      "    return func(*self.__args, **self.__kw)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/translation/__init__.py\", line 92, in gettext\n",
      "    return _trans.gettext(message)\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/utils/translation/__init__.py\", line 57, in __getattr__\n",
      "    if settings.USE_I18N:\n",
      "  File \"/Users/snarayan/anaconda3.7/anaconda3/lib/python3.7/site-packages/django/conf/__init__.py\", line 83, in __getattr__\n",
      "    self._setup(name)\n",
      "django.core.exceptions.ImproperlyConfigured: Requested setting USE_I18N, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.\n",
      "]\n"
     ]
    }
   ],
   "source": [
    "%%writefile  mangorest/mango.py\n",
    "#!/usr/local/bin/python\n",
    "import sys, os,datetime, pkgutil, inspect,hashlib, json, django\n",
    "from django.conf.urls import url\n",
    "from django.urls import path\n",
    "from django.shortcuts import render\n",
    "from django.http import HttpResponse, JsonResponse\n",
    "from django.contrib.auth.decorators import login_required\n",
    "from django.core.files.storage import default_storage\n",
    "from django.core.files.base import ContentFile\n",
    "from django.core.serializers.json import DjangoJSONEncoder\n",
    "from django.conf import settings\n",
    "from django.core.wsgi import get_wsgi_application\n",
    "from django.core.management import execute_from_command_line\n",
    "import numpy as np\n",
    "\n",
    "'''\n",
    "References: \n",
    "https://blog.miguelgrinberg.com/post/the-ultimate-guide-to-python-decorators-part-iii-decorators-with-arguments\n",
    "https://simpleisbetterthancomplex.com/article/2017/08/07/a-minimal-django-application.html\n",
    "\n",
    "'''\n",
    "__VERSION__ = \"1.0\"\n",
    "PORT        = 9000\n",
    "#--------------------------------------------------------------------------------\n",
    "def index(request):\n",
    "    return HttpResponse(f\"Version: {__VERSION__}\");\n",
    "#--------------------------------------------------------------------------------\n",
    "DEBUG=0\n",
    "def logp(*args, **kwargs):\n",
    "    if not DEBUG:\n",
    "        return;\n",
    "    \n",
    "    for c in kwargs:\n",
    "        print(kwargs[c], end=\" \")\n",
    "    for c in args:\n",
    "        print(c, end=\" \")\n",
    "    print()\n",
    "#--------------------------------------------------------------------------------\n",
    "def Debug(request, APPNAME=''):\n",
    "    rpath = request.path.split('/')[-2] #en(APPNAME)+2:-1]\n",
    "    template = \"/templates/\" + rpath;\n",
    "    pyModule = rpath;\n",
    "    \n",
    "    logp(f\"{template} Requested\")\n",
    "    getlist = [ c for c in request.GET.items()]\n",
    "    ret = f''' <pre>\\n Response Object: \\n{os.getcwd()} path_info:{request.path_info}: final:{rpath}\n",
    "               Page exists:  {template} : {os.path.exists(template)}\n",
    "               Page exists:  {pyModule} : {os.path.exists(pyModule)}\n",
    "               {getlist} </pre> '''\n",
    "    return HttpResponse(ret);\n",
    "#--------------------------------------------------------------------------------\n",
    "# ALL you need to do is just define a function as follows\n",
    "# def test(a=n, **kwargs):\n",
    "#    #do your stuff\n",
    "#    return \n",
    "# This function will take care of the rest\n",
    "\n",
    "class myEncoder(DjangoJSONEncoder):\n",
    "    def default(self, obj):\n",
    "        logp(\"============>. {obj} {typeof(obj)}\")\n",
    "        if isinstance(obj, np.int64):\n",
    "            return int(obj)\n",
    "        else:\n",
    "            return super(DjangoJSONEncoder, self).default(obj)\n",
    "#--------------------------------------------------------------------------------\n",
    "def CallMethod(method, request, args=None):\n",
    "    if(args is None):\n",
    "        args = inspect.getfullargspec(method)\n",
    "    \n",
    "    if (args.varkw == None ):\n",
    "        #logp(f\"ViewCommon: No kwargs?:Calling ...{method}(request)\");\n",
    "        return method(request)\n",
    "    \n",
    "    #logp(f\"ViewCommon: KWARGS:Calling ...\");\n",
    "    par = dict(request.GET)\n",
    "    par.update(request.POST)\n",
    "    \n",
    "    #paramters comes in as arrays \n",
    "    for k in par.keys():\n",
    "        if len(par[k]) <= 1:\n",
    "            par[k] = par[k][-1]  \n",
    "    \n",
    "    par[\"request\"] = request\n",
    "\n",
    "    ret = method(**par)\n",
    "    if ('content_type' in par and par['content_type'] == 'json'):\n",
    "        if (type(ret) == str):\n",
    "            ret = json.loads(ret)\n",
    "            \n",
    "        return JsonResponse(ret, safe=False)\n",
    "    \n",
    "    #logp(f'returning {ret} {type(ret)}')\n",
    "    \n",
    "    if (isinstance(ret, django.http.response.HttpResponseBase) ):\n",
    "        return ret;\n",
    "    \n",
    "    if (type(ret) != str):\n",
    "        ret = json.dumps(ret, cls=myEncoder)\n",
    "        \n",
    "    return HttpResponse(ret) #, content_type=\"text/plain\")\n",
    "#--------------------------------------------------------------------------------\n",
    "def TryRunPyMethod(request):\n",
    "    rpaths = [c for c in request.path.split(\"/\") if (c) ];\n",
    "    pyMethod = rpaths[-1];\n",
    " \n",
    "    #logp(f\"importing ... {pyMethod} ...\")\n",
    "    if ( pyMethod.find(\"modules.\") < 0 ):\n",
    "        return HttpResponse(f\"{pyMethod} not understood 0\")\n",
    "        \n",
    "    spl = pyMethod.split('.');\n",
    " \n",
    "    if ( len(spl) < 2):\n",
    "        logp(\"Hmmm ... May be not what is intended!! module name\")\n",
    "        return HttpResponse(f\"{pyMethod} not understood 2\");\n",
    "    \n",
    "    modName = \".\".join(spl[:-1])\n",
    "    __import__(modName, fromlist=\"dummy\")\n",
    "    \n",
    "    funName = spl[-1]\n",
    "    for v in sys.modules:\n",
    "        if (v.startswith(modName)):\n",
    "            method= getattr(sys.modules[v], funName)\n",
    "            logp(\"==>\", v, type(v), funName, method, type(method), callable(method))\n",
    "            return CallMethod(method, request)\n",
    "        \n",
    "    return HttpResponse(f\"{pyMethod} not understood3 \");\n",
    "    \n",
    "#--------------------------------------------------------------------------------\n",
    "'''\n",
    "USE following methods to pass in AUTH Key:\n",
    "    curl -i -H \"APK: 123\"  http://localhost:9000\n",
    "'''\n",
    "def AuthorizeAPIKEY(request):\n",
    "    apk = request.headers.get(\"APK\", \"\")\n",
    "    apk = apk or request.GET.get(\"APK\", \"?\")\n",
    "    apk = apk or request.POST.get(\"APK\", \"\")\n",
    "    # print(f\"====> FOUND {request.path} {apk} ++\")\n",
    "    # Validate APK Key and return \"Eror Description\"\n",
    "\n",
    "def AuthorizeNone(request):\n",
    "        return \"\"\n",
    "    \n",
    "AUTH_METHOD = AuthorizeNone\n",
    "#--------------------------------------------------------------------------------\n",
    "@login_required(login_url='/accounts/login/')\n",
    "def CommonSecured(request, apage):\n",
    "    return render(request, apage)\n",
    "#--------------------------------------------------------------------------------\n",
    "def Common(request):\n",
    "    path = request.path[:-1] if request.path.endswith(\"/\") else request.path\n",
    "    if ( path.endswith(\"favicon.ico\")):\n",
    "        return HttpResponse(f\"{path}!!\");\n",
    "    \n",
    "    # Check for authorizaton and version request\n",
    "    authError = AUTH_METHOD(request)\n",
    "    if ( authError ):\n",
    "        return HttpResponse(f\"{path} -- {authError}!!\");\n",
    "\n",
    "    # Next STEP 1: check with registered URLS\n",
    "    logp(f'*Check: {path} registered URLS: {_WEBAPI_ROUTES.keys()}')\n",
    "    \n",
    "    if (path in _WEBAPI_ROUTES.keys() ):\n",
    "        f, args, auth, opts = _WEBAPI_ROUTES[path]\n",
    "        if ( auth ):\n",
    "            ret = auth(request)\n",
    "            if ( ret ):\n",
    "                return HttpResponse(f\"{path} -- {authError}!!\"); \n",
    "        return CallMethod(f,request, args)\n",
    "\n",
    "\n",
    "    # If not in the registered do templates:\n",
    "    \n",
    "    rpaths = [c for c in path.split(\"/\") if (c)];\n",
    "    if (len(rpaths) < 1):\n",
    "        return index(request)\n",
    "    \n",
    "    template = f\"{rpaths[0]}/templates/{'/'.join(rpaths[1:])}\";\n",
    "    rpath    = \"/\".join(rpaths[1:]);\n",
    "    \n",
    "    logp(rpaths, f'=*=>{path} {template}; {rpaths} ++ {rpath}');\n",
    "    \n",
    "    if ( os.path.exists(template) and request.path.find(\"/secured/\") > 0) : \n",
    "        logp(\"Secured ==> \" , rpaths, \"==>\", template);\n",
    "        return CommonSecured(request, rpath)\n",
    "    elif ( os.path.exists(template) ):\n",
    "        return render(request, rpath)\n",
    "    elif rpaths[-1].find(\"services.\") >= 0: #Must be a python module call\n",
    "        logp(\"**** Getting python Module\")\n",
    "        return TryRunPyMethod(request)\n",
    "    \n",
    "    return HttpResponse(f\"{path} not understood\");\n",
    "    \n",
    "#--------------------------------------------------------------------------------\n",
    "_WEBAPI_ROUTES={}\n",
    "def webapi(url, auth=None, **kwargs):\n",
    "    if auth and not inspect.isfunction(auth):\n",
    "        auth = AuthorizeAPIKEY\n",
    "        \n",
    "    if type(url) is not str:\n",
    "        f = url\n",
    "        url = f'/{f.__module__}.{f.__name__}'\n",
    "        m = inspect.getfullargspec(f)\n",
    "        print(f\"Registering url: {url} {f} {type(url)}\")\n",
    "        _WEBAPI_ROUTES[url] = [f, m, auth, kwargs]\n",
    "        \n",
    "        return f\n",
    "    \n",
    "    def inner_decorator(f):\n",
    "        if url in _WEBAPI_ROUTES:\n",
    "            print(f\"Warning: Duplicate registration: {url} \")\n",
    "\n",
    "        m = inspect.getfullargspec(f)\n",
    "        url1 = url if url.startswith(\"/\") else \"/\"+url\n",
    "        url1 = url1[:-1] if url1.endswith(\"/\") else url1\n",
    "        \n",
    "        _WEBAPI_ROUTES[url1] = [f, m, auth, kwargs]\n",
    "\n",
    "        return f\n",
    "\n",
    "    return inner_decorator\n",
    "#----------------------------------------------------------------------------------\n",
    "def inJupyter():\n",
    "    try:    get_ipython; return True\n",
    "    except: return False\n",
    "#--------------------------------------------------------------------------------\n",
    "SECRET        = f'{os.name}{os.getcwd()}{datetime.datetime.now()}'\n",
    "DEBUG         = True\n",
    "SECRET_KEY    = hashlib.sha224(bytes(SECRET, 'utf-8')).hexdigest()\n",
    "ALLOWED_HOSTS = ['*']\n",
    "#--------------------------------------------------------------------------------\n",
    "def main():\n",
    "    os.environ.setdefault('DJANGO_SETTINGS_MODULE', __file__)\n",
    "    settings.configure(\n",
    "            DEBUG                 = DEBUG,\n",
    "            SECRET_KEY            =  SECRET_KEY,\n",
    "            ROOT_URLCONF          = __name__,\n",
    "            BASE_DIR              =  os.getcwd(),\n",
    "            ALLOWED_HOSTS         = ALLOWED_HOSTS,\n",
    "            CORS_ORIGIN_ALLOW_ALL = True,   \n",
    "            CSRF_COOKIE_HTTPONLY  = False,\n",
    "            CSRF_COOKIE_SECURE    = False,\n",
    "            AUTHORIZE             = \"\", #Can be a Function, method,\n",
    "            MIDDLEWARE_CLASSES=(\n",
    "                'django.middleware.common.CommonMiddleware',\n",
    "            ),\n",
    "        )\n",
    "    \n",
    "    argv = [c for c in sys.argv]\n",
    "    if len(argv) <= 1:\n",
    "        print(f\"** NOTICE ***\\n\\nTry running: {sys.argv[0]} runserver 0:9000 #to run on port 9000\\n***\\n\")\n",
    "        argv.extend([\"runserver\", f\"0:{PORT}\"])\n",
    "    execute_from_command_line(argv)\n",
    "\n",
    "urlpatterns = (\n",
    "    url(r'^.*', Common, name='catchall'),\n",
    ")\n",
    "    \n",
    "if __name__ == '__main__' and not inJupyter():\n",
    "    main()\n",
    "    pass"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 57,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Writing mangorest/dirlist.py\n"
     ]
    }
   ],
   "source": [
    "%%writefile  mangorest/dirlist.py\n",
    "#!/usr/local/bin/python\n",
    "'''\n",
    "Directory Listing Service\n",
    "'''\n",
    "import os, sys, datetime, re, json, importlib, glob\n",
    "from django.http import HttpResponse, JsonResponse,FileResponse\n",
    "import mangorest.mango\n",
    "from   mangorest.mango import webapi\n",
    "import mimetypes\n",
    "\n",
    "base = \"/opt/data/ANALYSIS/data\"\n",
    "\n",
    "@webapi(\"/data\")\n",
    "def dirlist(**kwargs):\n",
    "    \n",
    "    if (kwargs.get(\"file\" , None)):\n",
    "        f = kwargs.get(\"file\")\n",
    "        if ( not os.path.isfile(f) ):  \n",
    "            return f\"{f} is not a file\"\n",
    "        \n",
    "        response = FileResponse(open(f, 'rb'))\n",
    "        ct = list(response._headers['content-type'])\n",
    "        #print(f\" ==> {vars(response)} {ct}\") \n",
    "        if ( ct[1] == \"text/csv\"):\n",
    "            ct[1] = \"text/html\"\n",
    "            \n",
    "        #print(f\" ==> {response.headers['Content-Type']} \") \n",
    "        return response\n",
    "        \n",
    "    dirs= kwargs.get(\"base\" , f\"{base}/*\")\n",
    "    req = kwargs.get(\"request\", None)\n",
    "    url = (req and req.build_absolute_uri()) or \"http://localhost:80/data/\"\n",
    "    url = url.split('?')[0].strip('/')\n",
    "    \n",
    "    print(f\"===>  {dirs} {url}\")\n",
    "    if ( os.path.isdir(dirs)):\n",
    "        dirs = dirs + \"/**\"\n",
    "        \n",
    "    fil = glob.glob(f'{dirs}', recursive=True)\n",
    "    \n",
    "    ret = \"\".join([f'<li><a href={url}?file={f}>{url}?file={f}</a>' for f in fil])\n",
    "    return f\"<h1>Directory listing for: {base} </h1><br/>\" + ret\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Create Some Examples"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Writing test/simple.py\n"
     ]
    }
   ],
   "source": [
    "%%writefile  test/simple.py\n",
    "#!/usr/local/bin/python\n",
    "import mangorest.mango\n",
    "import myfile\n",
    "    \n",
    "mangorest.mango.__VERSION__ = \"1.1\"\n",
    "mangorest.mango.PORT        = 9000\n",
    "if __name__ == '__main__' and not mangorest.mango.inJupyter():\n",
    "    print(f'** NOTICE *** registered URLS: {mangorest.mango._WEBAPI_ROUTES.keys()}')\n",
    "    mangorest.mango.main()\n",
    "    pass    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 40,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Registering url: /__main__.ws1 <function ws1 at 0x7f9e58178ea0> <class 'str'>\n"
     ]
    }
   ],
   "source": [
    "#%%writefile  test/myfile.py\n",
    "from  mangorest.mango import webapi\n",
    "\n",
    "@webapi\n",
    "def ws1(h='param1', **kwargs):\n",
    "    ret = (f\"Web Service {h} {kwargs}\")\n",
    "    return ret\n",
    "\n",
    "@webapi(\"/ws2\")\n",
    "def ws2(**kwargs):\n",
    "    ret = (f\"Web service 2 {kwargs}\")\n",
    "    return ret"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# ALL in one file"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 33,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Overwriting test/test.py\n"
     ]
    }
   ],
   "source": [
    "%%writefile  test/test.py\n",
    "#!/usr/local/bin/python\n",
    "import mangorest.mango\n",
    "from   mangorest.mango import webapi\n",
    "\n",
    "@webapi\n",
    "def test1(h='test1', **kwargs):\n",
    "    ret = (f\"Hello Test1 {h} {kwargs}\")\n",
    "    print(ret)\n",
    "    return ret\n",
    "\n",
    "@webapi(\"/app1/testingroot2/\")\n",
    "def test2(request, h=\"test2\", **kwargs):\n",
    "    ret = (f\"Hello Test2 {h} {kwargs} {request.headers}\")\n",
    "    ret = (f\"Hello Test2 {h} {kwargs}\")\n",
    "\n",
    "    print(ret)\n",
    "    return ret\n",
    "\n",
    "mangorest.mango.__VERSION__ = \"1.1\"\n",
    "mangorest.mango.PORT        = 9001\n",
    "if __name__ == '__main__' and not mangorest.mango.inJupyter():\n",
    "    print(f'** NOTICE *** registered URLS: {mangorest.mango._WEBAPI_ROUTES.keys()}')\n",
    "    mangorest.mango.main()\n",
    "    pass\n"
   ]
  }
 ],
 "metadata": {
  "hide_input": false,
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.3"
  },
  "toc": {
   "base_numbering": 1,
   "nav_menu": {},
   "number_sections": true,
   "sideBar": true,
   "skip_h1_title": false,
   "title_cell": "Table of Contents",
   "title_sidebar": "Contents",
   "toc_cell": false,
   "toc_position": {},
   "toc_section_display": true,
   "toc_window_display": false
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
